---
title: "Time series analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r, echo=FALSE}
library("shiny")
library("shinyjs")
library("shinythemes")
library("shinydashboard")
#library("tidyverse")
library("quantmod")
library('dygraphs')
library('dplyr')
library('lubridate')
library('seasonal')
library('tseries')
library('forecast')
source('main.R')

test <- read.table('data.csv',header=TRUE,sep=',',colClasses=c("Date", rep("numeric", 1)))
test <- as.xts(test[-1], order.by=test[[1]])
data <- tsExt(test, 'Time series', 'daily')
```

## This is a report generated by the application

### Graph 

```{r}
plot_ts(data)
```


### Simple statistics


```{r}
summary(data)
```


## Seasonality analysis

### Tests

```{r}
test_season(data, input$seas_test)
```


### Graph

```{r}
 plot_test(data, type = 'season', seas_type='multiplicative')
```

## Stationarity analysis

### Tests

```{r}

test_station(data, input$station_test, as.integer(input$station_diff))
```

### Graph

```{r}
plot_test(data, type = 'station', n_dif=1)
```

## Forecasting

### Graph

```{r}
predict_ts(data, steps = 5, method = 'all', graph=TRUE)
```

### Forecast errors

```{r}
predict_ts(data, steps = 5, method = 'all', graph=FALSE)
```

